### ISSUE TITLE
Best chkpt

### ISSUE THREAD

**Issue by rahulvigneswaran** [tqch/v-diffusion-torch#2]
How to choose the best checkpoint from all the saved checkpoints?

**Comment by tqch** [comment]
One way to choose the best checkpoint is to simply compare the *Fréchet inception distance* (FID) between the generated samples and the training samples, 50k each. `generate.py` is used for image generation. For FID or Precision/Recall calculation, you can use the script in my other repo [link](https://github.com/tqch/ddpm-torch/blob/master/eval.py)

**Comment by rahulvigneswaran** [comment]
`eval.py` from the repo you pointed to is throwing alot of errors due to some differences between the repos. By any chance can you post the one you used for selecting the best chkpt?

**Comment by rahulvigneswaran** [comment]
`torch.cdist()` doesn't support half precision. So converting the features into `float32` and back during the `torch.cdist()` fixes the issues. Can you point me to a resource that says how to choose a chkpt based on PR and recall - that is, what is the desired PR and recall.

@tqch

**Comment by tqch** [comment]
I've uploaded the `eval.py` for this repo in the new commit. While precision and recall do give you certain sense of how well the model is doing in generation fidelity and diversity respectively, there is no universal standards determining whether a value is indeed good or not. The goodness of PR results [[paper]](https://arxiv.org/pdf/1904.06991.pdf) is dependent on the dataset and how currently other generative models perform. However, there aren't many recent papers actually report those metrics. The most widely used metrics on image generation quality are still FID and IS. As for choosing the best checkpoint, using these metrics to choose checkpoints is not always necessary. As a rule of thumb, the performance of diffusion-based models usually improves (at least not degrading) over training. In other words, you can always take the latest checkpoint as your final model.
