### ISSUE TITLE
Epsilon-prediction

### ISSUE THREAD

**Issue by BurgerAndreas** [tqch/v-diffusion-torch#4]
Hi, thank you for the repo!

Does it support noise-prediction instead of v-prediction?

What would one need to change to implement noise-prediction?

**Comment by tqch** [comment]
Yes, it does.

The following changes by either modifying a JSON config file or specifying as command line arguments will suffice, namely

a).
`model_out_type: "eps"`
`reweight_type: "snr"`

b).
--model-out-type eps
--reweight-type snr
